apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: flask-env-var
spec:
  secretName: flask-env-var-cert-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'flask.fsainovich.xyz'
  dnsNames:
    - 'flask.fsainovich.xyz'
