apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:  
    name: ingress-2048
    namespace: game-2048
spec:
  rules:
    - host: 2048.fsainovich.xyz
      http:
        paths:
        - backend:
            service:
              name: service-2048
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - 2048.fsainovich.xyz
      secretName: 2048-cert-tls
