apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2048
  namespace: game-2048
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingressClassName: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: 2048.fsainovich.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-2048
            port:
              number: 80
  tls:
  -  hosts:
     - 2048.fsainovich.xyz
     secretName: 2048-cert-tls
